### ISSUE TITLE
temp tables

### ISSUE THREAD

**Issue by ikitiki** [ikitiki/logical_backup#32]
Looks like sometimes we're trying to backup temp tables:
```
2018/11/07 09:42:10 could not basebackup "public"."pg_temp_180104": could not lock table: could not lock the table: ERROR: relation "public.pg_temp_180104" does not exist (SQLSTATE 42P01)
```

**Comment by alexeyklyukin** [comment]
The issue is that we may attempt to backup the table that has been dropped in the database (the actual table here is not a temp one, as it resides in the public namespace); to resolve the issue we can check if the table exists before moving forward with the backup.

**Comment by alexeyklyukin** [comment]
Solved with https://github.com/ikitiki/logical_backup/commit/c65989a5ccc461722e9e57a962721df5bbb84132
